juliamarco/little_shop

Little Shop DTR.md

Co-authored-by:  Earl Stephens <34906415+earl-stephens@users.noreply.github.com>
Co-authored-by:  Jennica Stiehl <25069483+stiehlrod@users.noreply.github.com>

Adds DTR file to root folder

---

app/controllers/items_controller.rb
app/models/item.rb
app/views/items/index.html.erb
config/routes.rb
db/migrate/20190210234851_change_description_in_items_table_to_be_string.rb
db/migrate/20190211153341_change_prices_to_float.rb
db/migrate/20190211153618_change_order_items.rb
db/schema.rb
spec/features/items/items_index_spec.rb
spec/rails_helper.rb

- Added first test for displaying all items in the system 
- Added basic functionality for passing test

Items index page

---

app/controllers/admin/base_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/application_controller.rb
app/controllers/welcome_controller.rb
app/models/user.rb
app/views/admin/users/index.html.erb
app/views/layouts/application.html.erb
app/views/welcome/index.html.erb
config/routes.rb
db/migrate/20190211222318_delete_role_column.rb
db/migrate/20190211222415_create_user_role_column.rb
db/schema.rb
spec/features/nav_bar_spec.rb
spec/models/user_spec.rb

Authorization will need a bit of cleaning after authentication is merged in 👍

Authorization

---

.rspec
Gemfile
Gemfile.lock
app/controllers/users_controller.rb
app/controllers/welcome_controller.rb
app/models/user.rb
app/views/users/new.html.erb
app/views/users/show.html.erb
app/views/welcome/index.html.erb
config/routes.rb
db/migrate/20190211214551_change_users_role.rb
db/schema.rb
spec/features/user_registration_spec.rb
spec/models/user_spec.rb
spec/rails_helper.rb

started work on authentication

Authentication

---

app/controllers/application_controller.rb
app/controllers/merchant/base_controller.rb
app/controllers/merchant/users_controller.rb
app/models/order.rb
app/views/layouts/application.html.erb
app/views/merchant/users/index.html.erb
app/views/welcome/index.html.erb
config/routes.rb
spec/features/nav_bar_spec.rb
spec/features/visitor_spec.rb

Co-authored-by: Julia Marco <35079289+juliamarco@users.noreply.github.com>
navigation
-adds links to home, merchants, spices, registration and logging in

functionality for navigation bar

---

app/views/users/show.html.erb
config/routes.rb
spec/features/user/show_spec.rb

Co-authored-by: Trevor Nodland <42710030+tnodland@users.noreply.github.com>
#57 :user show page

adds user story #17

---

app/controllers/application_controller.rb
app/controllers/carts_controller.rb
app/controllers/sessions_controller.rb
app/models/cart.rb
app/views/items/index.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/items/items_index_spec.rb
spec/features/nav_bar_spec.rb
spec/models/cart_spec.rb

finishes story 2 with a cart and it's total items
closes #76

Finish story 2

---

DTR2.md

Co-authored-by: Earl Stephens <34906415+earl-stephens@users.noreply.github.com>
Co-authored-by: Trevor Nodland <42710030+tnodland@users.noreply.github.com>
Co-authored-by: Julia Marco <35079289+juliamarco@users.noreply.github.com>

Adds second DTR

---

app/controllers/merchant/users_controller.rb
app/views/merchant/users/show.html.erb
config/routes.rb
spec/features/merchant/merhcant_dashboard_spec.rb

Co-authored-by: Jennica Stiehl <25069483+stiehlrod@users.noreply.github.com>

finishes usert story 39

---

db/migrate/20190214205919_change_order_item_fulfilled_column_to_boolean.rb
db/schema.rb

Co-authored-by:  Earl Stephens <34906415+earl-stephens@users.noreply.github.com>
Co-authored-by:  Jennica Stiehl <25069483+stiehlrod@users.noreply.github.com>

Changed schema

---

app/views/layouts/application.html.erb
spec/features/admin/admin_can_see_user_index_spec.rb
spec/features/nav_bar_spec.rb

Added test and functionality for User Story 3

---

Gemfile.lock
app/controllers/admin/base_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/application_controller.rb
app/controllers/carts_controller.rb
app/controllers/items_controller.rb
app/controllers/orders_controller.rb
app/controllers/sessions_controller.rb
app/models/cart.rb
app/models/item.rb
app/models/order.rb
app/models/user.rb
app/views/carts/show.html.erb
app/views/welcome/index.html.erb
config/routes.rb
spec/features/cart/show_spec.rb
spec/features/nav_bar_spec.rb
spec/features/visitor_spec.rb
spec/models/cart_spec.rb
spec/models/item_spec.rb

adds model test passing at 100% coverage
adds user story 27 & 28

Card45story28

---

app/controllers/orders_controller.rb
app/models/order.rb
app/models/order_item.rb
app/views/orders/index.html.erb
config/routes.rb
spec/factories/order_items.rb
spec/features/user/order_show_spec.rb
spec/models/order_spec.rb

User Profile displays Orders
closes #39 

Added tests and functionality for User Story 33

---

app/controllers/orders_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/models/order.rb
app/models/order_item.rb
app/views/admin/users/index.html.erb
app/views/layouts/application.html.erb
app/views/merchant/users/show.html.erb
app/views/orders/index.html.erb
app/views/users/show.html.erb
app/views/welcome/index.html.erb
config/routes.rb
spec/factories/order_items.rb
spec/features/admin/admin_can_see_user_index_spec.rb
spec/features/admin/user_show_spec.rb
spec/features/user/order_show_spec.rb
spec/features/user/user_login_spec.rb
spec/models/order_spec.rb

User login

---

app/controllers/sessions_controller.rb
app/models/order.rb
spec/features/user/user_login_spec.rb

Added tests and functionality for users logged in redirection

---

app/controllers/sessions_controller.rb
app/models/order.rb
app/views/layouts/application.html.erb
spec/features/user/user_login_spec.rb
spec/features/user/user_logout_spec.rb

User can log out

---

app/controllers/sessions_controller.rb
app/models/order.rb
app/views/layouts/application.html.erb
spec/features/nav_bar_spec.rb
spec/features/user/user_login_spec.rb
spec/features/user/user_logout_spec.rb

Merchant navigation

---

app/controllers/carts_controller.rb
public/cart_login.html.erb
spec/features/cart/show_spec.rb

Added test and functionality for User Story 30

---

app/controllers/users_controller.rb
app/models/item.rb
app/views/layouts/application.html.erb
app/views/users/edit.html.erb
spec/features/admin/user_show_spec.rb
spec/features/user/user_edit_path_spec.rb
spec/models/order_spec.rb

completed user story 21 Admin can edit a user's profile data
closes#53

Story21card53

---

app/controllers/items_controller.rb
app/controllers/merchant/items_controller.rb
app/models/item.rb
app/models/order_item.rb
app/views/items/_form.html.erb
app/views/items/edit.html.erb
app/views/items/new.html.erb
app/views/merchant/items/index.html.erb
config/routes.rb
spec/features/merchant/items_page_spec.rb
spec/features/merchant/merchant_dashboard_spec.rb

Merge conflicts

---

app/controllers/items_controller.rb
app/controllers/merchant/items_controller.rb
app/models/item.rb
app/models/order_item.rb
app/views/items/_form.html.erb
app/views/items/edit.html.erb
app/views/items/new.html.erb
app/views/merchant/items/index.html.erb
config/routes.rb
spec/features/merchant/items_page_spec.rb
spec/features/merchant/merhcant_dashboard_spec.rb

closes #18 
closes 17 , except flash message

adds story52, card17

---

app/controllers/admin/users_controller.rb
app/controllers/items_controller.rb
app/controllers/merchant/items_controller.rb
app/models/item.rb
app/models/order_item.rb
app/views/admin/users/index.html.erb
app/views/items/_form.html.erb
app/views/items/edit.html.erb
app/views/items/new.html.erb
app/views/layouts/application.html.erb
app/views/merchant/items/index.html.erb
config/routes.rb
spec/features/admin/admin_can_see_user_index_spec.rb
spec/features/merchant/items_page_spec.rb
spec/features/merchant/merhcant_dashboard_spec.rb

Story65card2

---

app/controllers/admin/users_controller.rb
app/controllers/items_controller.rb
app/controllers/merchant/items_controller.rb
app/models/item.rb
app/models/order_item.rb
app/views/admin/users/index.html.erb
app/views/items/_form.html.erb
app/views/items/edit.html.erb
app/views/items/new.html.erb
app/views/layouts/application.html.erb
app/views/merchant/items/index.html.erb
config/routes.rb
spec/features/admin/admin_can_see_user_index_spec.rb
spec/features/merchant/items_page_spec.rb
spec/features/merchant/merhcant_dashboard_spec.rb
spec/features/merchant/order_show_spec.rb

this is only the test setup because I need conflicts resolved/merged. I don't want to create more conflicts with the routes/namespacing.

Story60card8

---

app/controllers/admin/merchants_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/items_controller.rb
app/controllers/merchant/items_controller.rb
app/models/item.rb
app/models/order_item.rb
app/views/admin/merchants/show.html.erb
app/views/admin/users/edit.html.erb
app/views/admin/users/index.html.erb
app/views/items/_form.html.erb
app/views/items/edit.html.erb
app/views/items/new.html.erb
app/views/layouts/application.html.erb
app/views/merchant/items/index.html.erb
config/routes.rb
spec/features/admin/admin_can_see_user_index_spec.rb
spec/features/admin/merchant_dashboard_spec.rb
spec/features/merchant/items_page_spec.rb
spec/features/merchant/merhcant_dashboard_spec.rb
spec/features/merchant/order_show_spec.rb

Story44card27

---

app/controllers/admin/merchants_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/items_controller.rb
app/controllers/merchant/items_controller.rb
app/models/item.rb
app/models/order_item.rb
app/views/admin/merchants/show.html.erb
app/views/admin/users/edit.html.erb
app/views/admin/users/index.html.erb
app/views/items/_form.html.erb
app/views/items/edit.html.erb
app/views/items/new.html.erb
app/views/layouts/application.html.erb
app/views/merchant/items/index.html.erb
config/routes.rb
spec/features/admin/admin_can_see_user_index_spec.rb
spec/features/admin/merchant_dashboard_spec.rb
spec/features/merchant/items_page_spec.rb
spec/features/merchant/merhcant_dashboard_spec.rb
spec/features/merchant/order_show_spec.rb

Story45card26

---

app/controllers/items_controller.rb
app/controllers/merchant/items_controller.rb
app/views/admin/users/show.html.erb
app/views/merchant/items/index.html.erb
app/views/merchant/items/new.html.erb
app/views/merchant/users/show.html.erb
config/routes.rb
db/migrate/20190218215759_give_items_default_image.rb
db/schema.rb
db/seeds.rb
spec/features/admin/user_show_spec.rb
spec/features/merchant/items_page_spec.rb
spec/features/nav_bar_spec.rb

before merging and closing this branch we need to change the active status of items to default to true
closes #14

Story 55 card 14

---

app/controllers/admin/merchants_controller.rb
app/views/admin/merchants/index.html.erb
config/routes.rb
spec/features/admin/merchant_index_page_spec.rb

closes #28
Hey guys, I think we will have to come back to this just to make sure the admin sees exactly the same as the merchant in his dashboard, but I believe this will be achievable with a partial once our dashboard for the merchant is completed. Also, please check the routes file cause I did some changes. 
The last person to review it can go ahead and merge!

Admin sees merchant dashboard

---

app/controllers/admin/merchants_controller.rb
app/views/admin/merchants/index.html.erb
config/routes.rb
spec/features/admin/admin_can_see_user_index_spec.rb
spec/features/admin/merchant_index_page_spec.rb

closes #22 
closes #20
closes #21
Wondering if we need a view for merchants index page, or should users be enough?

Admin visits merchant index page

---

app/controllers/admin/merchants_controller.rb
app/controllers/merchant/items_controller.rb
app/controllers/merchant/orders_controller.rb
app/models/order.rb
app/views/admin/merchants/index.html.erb
app/views/merchant/orders/show.html.erb
config/routes.rb
spec/features/admin/admin_can_see_user_index_spec.rb
spec/features/admin/merchant_index_page_spec.rb
spec/features/merchant/order_show_spec.rb

Merchant sees order show page

---

app/controllers/items_controller.rb
app/controllers/merchant/items_controller.rb
app/views/merchant/items/index.html.erb
app/views/merchant/users/show.html.erb
spec/features/merchant/items_page_spec.rb

Merchant enables item

---

app/controllers/merchant/orders_controller.rb
app/controllers/order_items_controller.rb
app/models/item.rb
app/views/merchant/orders/show.html.erb
config/routes.rb
spec/features/merchant/order_show_spec.rb
spec/models/item_spec.rb

Merchant fulfills part of an order

---

app/assets/stylesheets/application.css
app/views/merchant/orders/show.html.erb
spec/features/merchant/order_show_spec.rb

Merchant cannot fulfill order

---

app/controllers/order_items_controller.rb
app/controllers/orders_controller.rb
app/models/order.rb
db/migrate/20190217213005_change_order_table.rb
spec/features/merchant/order_show_spec.rb
spec/features/user/order_show_spec.rb
spec/models/order_spec.rb

Order changes status

---

app/controllers/users_controller.rb
app/models/order.rb
app/models/order_item.rb
app/views/users/index.html.erb
spec/features/merchant/merchants_index_spec.rb

adds last 2 statistics
closes #23

adds fastest and slowest merchants

---

app/controllers/orders_controller.rb
app/models/item.rb
app/views/merchant/users/show.html.erb
app/views/orders/show.html.erb
spec/features/merchant/items_page_spec.rb
spec/features/merchant/merchant_dashboard_spec.rb
spec/features/user/order_show_spec.rb

User views order show page

---

app/assets/stylesheets/application.css
app/controllers/admin/orders_controller.rb
app/controllers/order_items_controller.rb
app/controllers/orders_controller.rb
app/models/item.rb
app/models/order.rb
app/views/admin/orders/show.html.erb
app/views/admin/users/show.html.erb
app/views/layouts/application.html.erb
app/views/merchant/orders/show.html.erb
app/views/merchant/users/show.html.erb
app/views/orders/show.html.erb
db/migrate/20190217213005_change_order_table.rb
spec/features/admin/user_show_spec.rb
spec/features/merchant/items_page_spec.rb
spec/features/merchant/merchant_dashboard_spec.rb
spec/features/merchant/order_show_spec.rb
spec/features/user/order_index_spec.rb
spec/features/user/order_show_spec.rb
spec/models/order_spec.rb

Admin sees user orders

---

app/controllers/admin/orders_controller.rb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
config/routes.rb
spec/features/admin/user_show_spec.rb

Added user story 35

---

app/controllers/admin/orders_controller.rb
app/controllers/order_items_controller.rb
app/views/admin/orders/show.html.erb
app/views/merchant/orders/show.html.erb
spec/features/admin/user_show_spec.rb
spec/features/item_show_spec.rb
spec/features/merchant/order_show_spec.rb

Admin can fulfill order

---

app/controllers/admin/merchants_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/sessions_controller.rb
app/views/admin/users/index.html.erb
app/views/admin/users/show.html.erb
config/routes.rb

Co-authored-by:  Earl Stephens <34906415+earl-stephens@users.noreply.github.com>
Co-authored-by:  Jennica Stiehl <25069483+stiehlrod@users.noreply.github.com>

Extra changes

---

app/controllers/carts_controller.rb
app/models/order.rb
app/models/order_item.rb
app/views/orders/show.html.erb

Co-authored-by:  Earl Stephens <34906415+earl-stephens@users.noreply.github.com>
Co-authored-by:  Jennica Stiehl <25069483+stiehlrod@users.noreply.github.com>

Some refactoring

---

app/models/item.rb
spec/models/items_spec.rb
spec/models/order_items_spec.rb
spec/models/order_spec.rb
spec/models/user_spec.rb

adds more model coverage

---

spec/models/order_spec.rb
spec/models/user_spec.rb

adds more coverage

---

spec/models/item_spec.rb

worked on item model test
